{{--Subject line: Invitation to be a PC member or Reviewer--}}

Note: The following message is automatically generated by the ConferenceClick conference management system. Do not reply to this email.

Dear, {{$nameTitlePrefix}} {{ $name }},

@foreach($ConferenceName as $confName)
You are invited by {{$SenderName}} to be a PC member or Reviewer to {{$confName->conferenceName}}.
@endforeach

Please register here if you are keen:

http://localhost/auth/show/{{$ConferenceId}}?email={{ $email }}

For more information, please visit the conference website:

Please do not hesitate to contact {{ $SenderEmail }} for enquiries.

Yours truly,

The ConferenceClick Admin


